# Generated by Django 5.0.3 on 2024-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOfferModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('title', models.TextField(max_length=100)),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('newPrice', models.CharField(max_length=50)),
                ('oldPrice', models.CharField(max_length=50)),
            ],
        ),
    ]
