# Generated by Django 5.0.3 on 2024-04-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_offers', '0002_alter_specialoffermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffermodel',
            name='image',
            field=models.TextField(),
        ),
    ]
