# Generated by Django 5.0.3 on 2024-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0004_alter_icecreammodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreammodel',
            name='title',
            field=models.TextField(),
        ),
    ]
