# Generated by Django 5.0.3 on 2024-04-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0005_alter_icecreammodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreammodel',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='icecreammodel',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
