# Generated by Django 5.0.3 on 2024-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ordersImages/')),
                ('title', models.CharField(max_length=100)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('count', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('delivered', models.BooleanField(default=False)),
                ('operationNumber', models.CharField(max_length=50)),
            ],
        ),
    ]
