# Generated by Django 5.0.3 on 2024-04-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_category_remove_order_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.CharField(max_length=50),
        ),
    ]
