# Generated by Django 5.0.3 on 2024-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_location_order_phonenumber_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='operationNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
